inherit_from: .rubocop_todo.yml
require:
    - rubocop-rails
    - rubocop-rspec
AllCops:
    Exclude:
        - db/**/*
        - config/**/*
        - bin/**/*
Style/Documentation:
    Exclude:
        - app/mailers/application_mailer.rb
        - app/models/application_record.rb
Metrics/BlockLength:
    Exclude:
        - spec/requests/monzo_hook_receiver_request_spec.rb