name: CI

on:
  pull_request:
  push:
    branches:
      - base

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Continuous integration
    services:
      bundle_cache:
        image: busybox
        volumes:
          - /github/raise-cache/vendor/bundle:/bundle_cache
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Fetch repository basename
        run: echo "::set-output name=name::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"
        id: repository_details
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /home/runner/work/${{ steps.repository_details.outputs.name }}/bundle_cache
            **/node_modules
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/yarn.lock') }}
      - name: Continuous integration step (scripts/cibuild)
        uses: whoan/docker-build-with-cache-action@v5
        env:
          GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
        with:
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: "${{ steps.repository_details.outputs.name }}"
          push_image_and_stages: docker run --network ${{ job.container.network }} --workdir /github/workspace -v /home/runner/work/${{ steps.repository_details.outputs.name }}/${{ steps.repository_details.outputs.name }}:/github/workspace -v /home/runner/work/${{ steps.repository_details.outputs.name }}/bundle_cache:/bundle_cache -e GITHUB_CLIENT_ID -e GITHUB_CLIENT_SECRET -e LINKEDIN_CLIENT_ID -e LINKEDIN_CLIENT_SECRET my_awesome_image:latest scripts/cibuild
      - name: Check coverage report is available
        if: always()
        id: check_coverage_report_exists
        uses: andstor/file-existence-action@v1
        with:
          files: "coverage/index.html"
      - name: Upload coverage report as artifact
        if: steps.check_coverage_report_exists.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/index.html
